
MODEL_LIST = {
    -- Couriers
    "models/courier/baby_rosh/babyroshan.vmdl",
    "models/courier/baby_rosh/babyroshan_winter18.vmdl",
    "models/courier/baby_winter_wyvern/baby_winter_wyvern.vmdl",
    "models/courier/badger/courier_badger.vmdl",
    "models/courier/beetlejaws/mesh/beetlejaws.vmdl",
    "models/courier/courier_mech/courier_mech.vmdl",
    "models/courier/defense3_sheep/defense3_sheep.vmdl",
    "models/courier/donkey_crummy_wizard_2014/donkey_crummy_wizard_2014.vmdl",
    "models/courier/donkey_ti7/donkey_ti7.vmdl",
    "models/courier/donkey_unicorn/donkey_unicorn.vmdl",
    "models/courier/doom_demihero_courier/doom_demihero_courier.vmdl",
    "models/courier/drodo/drodo.vmdl",
    "models/courier/frog/frog.vmdl",
    "models/courier/frull/frull_courier.vmdl",
    "models/courier/godhorse/godhorse.vmdl",
    "models/courier/gold_mega_greevil/gold_mega_greevil.vmdl",
    "models/courier/greevil/gold_greevil.vmdl",
    "models/courier/huntling/huntling.vmdl",
    "models/courier/imp/imp.vmdl",
    "models/courier/juggernaut_dog/juggernaut_dog.vmdl",
    "models/courier/lockjaw/lockjaw.vmdl",
    "models/courier/mech_donkey/mech_donkey.vmdl",
    "models/courier/mechjaw/mechjaw.vmdl",
    "models/courier/mega_greevil_courier/mega_greevil_courier.vmdl",
    "models/courier/mighty_boar/mighty_boar.vmdl",
    "models/courier/minipudge/minipudge.vmdl",
    "models/courier/navi_courier/navi_courier.vmdl",
    "models/courier/octopus/octopus.vmdl",
    "models/courier/otter_dragon/otter_dragon.vmdl",
    "models/courier/ram/ram.vmdl",
    "models/courier/seekling/seekling.vmdl",
    "models/courier/sillydragon/sillydragon.vmdl",
    "models/courier/skippy_parrot/skippy_parrot.vmdl",
    "models/courier/smeevil/smeevil.vmdl",
    "models/courier/smeevil_bird/smeevil_bird.vmdl",
    "models/courier/smeevil_crab/smeevil_crab.vmdl",
    "models/courier/smeevil_magic_carpet/smeevil_magic_carpet.vmdl",
    "models/courier/smeevil_mammoth/smeevil_mammoth.vmdl",
    "models/courier/snowleopard/snowleopard_courier.vmdl",
    "models/courier/tegu/tegu.vmdl",
    "models/courier/trapjaw/trapjaw.vmdl",
    "models/courier/turtle_rider/turtle_rider.vmdl",
    "models/courier/venoling/venoling.vmdl",
    "models/courier/yak/yak.vmdl",

    -- Couriers 2
    "models/items/courier/arneyb_rabbit/arneyb_rabbit.vmdl",
    "models/items/courier/azuremircourierfinal/azuremircourierfinal.vmdl",
    "models/items/courier/boris_baumhauer/boris_baumhauer.vmdl",
    "models/items/courier/bucktooth_jerry/bucktooth_jerry.vmdl",
    "models/items/courier/captain_bamboo/captain_bamboo.vmdl",
    "models/items/courier/chocobo/chocobo.vmdl",
    "models/items/courier/faceless_rex/faceless_rex.vmdl",
    "models/items/courier/fei_lian_blue/fei_lian_blue.vmdl",
    "models/items/courier/green_jade_dragon/green_jade_dragon.vmdl",
    "models/items/courier/guardians_of_justice_enix/guardians_of_justice_enix.vmdl",
    "models/items/courier/jilling_ben_courier/jilling_ben_courier.vmdl",
    "models/items/courier/mighty_chicken/mighty_chicken.vmdl",
    "models/items/courier/mole_messenger/mole_messenger_lvl7.vmdl",
    "models/items/courier/onibi_lvl_20/onibi_lvl_20.vmdl",
    "models/items/courier/onibi_lvl_21/onibi_lvl_21.vmdl",
    "models/items/courier/snapjaw/snapjaw.vmdl",
    "models/items/courier/tory_the_sky_guardian/tory_the_sky_guardian.vmdl",
    "models/items/courier/vigilante_fox_red/vigilante_fox_red.vmdl",
    "models/items/courier/virtus_werebear_t3/virtus_werebear_t3.vmdl",
    "models/items/courier/weta_automaton/weta_automaton.vmdl",
	
	-- Treasure Chests
	-- "models/props_gameplay/treasure_chest001.vmdl",
	-- "models/props_generic/chest_treasure_02.vmdl",
	-- "models/props_gameplay/treasure_chest_gold.vmdl",
	
	-- Wards    守卫
	-- "models/items/wards/esl_wardchest_woody/esl_wardchest_woody.vmdl",
	-- "models/items/wards/f2p_ward/f2p_ward.vmdl",
	-- "models/items/wards/fairy_dragon/fairy_dragon.vmdl",
	-- "models/items/wards/phoenix_ward/phoenix_ward.vmdl",
	-- "models/items/wards/portal_ward/portal_ward.vmdl",
	
    -- "Standard" items
    "models/props_gameplay/aegis.vmdl",
    "models/props_gameplay/banana_prop_open.vmdl",
    "models/props_gameplay/bottle_blue.vmdl",
    "models/props_gameplay/branch.vmdl",
    "models/props_gameplay/chicken.vmdl",
    "models/props_gameplay/cheese.vmdl",
	"models/props_gameplay/divine_rapier.vmdl",
	"models/props_gameplay/gem01.vmdl",
    "models/props_gameplay/mango.vmdl",
    "models/props_gameplay/pig.vmdl",
    "models/props_gameplay/salve.vmdl",
	"models/props_gameplay/salve_blue.vmdl",
	"models/props_gameplay/salve_red.vmdl",
    "models/props_gameplay/smoke.vmdl",
    "models/props_gameplay/tango.vmdl",
}
